version: '3'
services:
  data-generation:
    build: ./data-generation
    ports:
      - "8080:8080"
  data-processing:
    build: ./data-processing
    ports:
      - "8081:8080"
  collecting-metrics:
    build: ./collecting-metrics
    ports:
      - "8082:8080"