openapi: 3.0.1
info:
  title: Data Processing Service
  description: This service processes data from data generation service
  version: "1.0"
servers:
- url: http://data-processing:8081/data-processing
  description: Server url for docker
paths:
  /data/customCsv/{size}:
    get:
      tags:
      - data-processing-controller
      summary: convert to csv with given columns
      description: generates x=size random json object and converts them to csv format
        with given columns in 'columns' parameter
      operationId: convertToCSVWithGivenColumns
      parameters:
      - name: size
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: columns
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /data/csv/{size}:
    get:
      tags:
      - data-processing-controller
      summary: convert to csv
      description: generates x=size random json object and converts them to csv format
      operationId: convertToCSV
      parameters:
      - name: size
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /calculate/{size}:
    get:
      tags:
      - data-processing-controller
      summary: Perform operations
      description: "Generates x=size json objects with random data and perform mathematical\
        \ operations on them. Operations are passed in 'operations' parameter in format\
        \ 'operation1,operation2,operation3' etc. where operation is in format 'columnName1+columnName2'\
        \ or 'columnName1^columnName2' etc."
      operationId: performOperations
      parameters:
      - name: size
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: operations
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
